version: "3.8"
services:
    backend:
        build: ./backend
        container_name: backend
        ports:
            - "5100:5100"
        volumes:
            - ./backend:/app
            - /app/node_modules

    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

        environment:
            - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
            #- NODE_ENV=development
        depends_on:
            - backend
